In [2]:
import numpy as np

List vs Array
1. List cannot handle directly mathematical operation while array can.
2. Array consumes less memory
3. Array is faster than list
4. List can store different data types but you cannot do that with array

From a Python List / Tuple

In [21]:
arr1 = np.array([1, 2, 3])             # 1D array from list
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array from nested list
arr3 = np.array((5, 6, 7))             # 1D array from tuple
print(arr1)
print(arr2)
print(arr3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[5 6 7]


In [22]:
ar = np.array([1, 2, 3], dtype=np.float64)  # 1D array with specified data type
print(ar)
print(ar.dtype)  # Output: float64
print(ar.shape)  # Output: (3,)
print(ar.ndim)   # Output: 1 (number of dimensions)
print(ar.size)   # Output: 3 (number of elements)
print(type(ar))  # Output: <class 'numpy.ndarray'>

[1. 2. 3.]
float64
(3,)
1
3
<class 'numpy.ndarray'>


Using Built-in Initialization Functions

In [8]:
print(np.zeros((2, 3)))  # 2D array of zeros

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((2, 3)))   # 2D array of ones

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.empty((2, 3)))  # 2D array with uninitialized values

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.arange(10))  # 1D array with values from 0 to 9

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(np.linspace(0, 1, 5))  # 1D array with 5 evenly spaced values between 0 and 1

[0.   0.25 0.5  0.75 1.  ]


In [15]:
print(np.eye(3))  # 3x3 identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
print(np.full((2, 2), 7))  # 2D array filled with the value 7

[[7 7]
 [7 7]]


In [18]:
print(np.random.rand(5))  # 1D array with random values

[0.8176971  0.97719111 0.21854205 0.76018718 0.79119607]


In [19]:
print(np.random.rand(2, 3))  # 2D array with random values

[[0.69832909 0.54912694 0.41461452]
 [0.24003695 0.26226768 0.11615976]]


In [20]:
print(np.random.randint(0, 10, (2, 3)))  # 2D array with random integers between 0 and 10

[[2 1 0]
 [4 0 4]]
