In [1]:
import numpy as np

ar1 = np.array([[10, 20], [40, 50]])
ar2 = np.array([[30, 40], [70, 80]])

Mathematical Operation

In [3]:
print(ar1 + ar2)  # Element-wise addition
print(np.add(ar1,ar2))


[[ 40  60]
 [110 130]]
[[ 40  60]
 [110 130]]


In [4]:
print(ar1 - ar2)  # Element-wise subtraction
print(np.subtract(ar1, ar2))

[[-20 -20]
 [-30 -30]]
[[-20 -20]
 [-30 -30]]


In [5]:
print(ar1 * ar2)  # Element-wise multiplication
print(np.multiply(ar1, ar2))

[[ 300  800]
 [2800 4000]]
[[ 300  800]
 [2800 4000]]


In [6]:
print(ar1 / ar2)  # Element-wise division
print(np.divide(ar1, ar2))

[[0.33333333 0.5       ]
 [0.57142857 0.625     ]]
[[0.33333333 0.5       ]
 [0.57142857 0.625     ]]


In [ ]:
ar = np.array([[16, 25], [36, 64]])
print(np.sqrt(ar))  # Element-wise square root

[[4. 5.]
 [6. 8.]]


In [13]:
ar = np.array([[4, 5], [6, 8]])
print(ar**2)  # Element-wise square
print(pow(ar, ar2)) # Element-wise power(2)

[[16 25]
 [36 64]]
[[16 25]
 [36 64]]


In [12]:
ar = np.array([[4, 5], [6, 8]])
print(ar%2)  # Element-wise modulus
print(np.mod(ar, 2))

[[0 1]
 [0 0]]
[[0 1]
 [0 0]]
