Advance topics

In [1]:
import numpy as np

In [3]:
# insert elements at specific indices
ar = np.array([10, 20, 30, 40, 50])
new_arr = np.insert(ar, 2, 100)
print(new_arr)

[ 10  20 100  30  40  50]


In [4]:
# insert in 2D array
ar_2d = np.array([[1, 2, 3], [4, 5, 6]])
new_arr_2d = np.insert(ar_2d, 1, [7, 8, 9], axis=0)
print(new_arr_2d)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [10]:
ar_2D = np.array([[1, 2, 3], [4, 5, 6]])
new_ar = np.insert(ar_2D, 1, [7, 8], axis=1)
print(new_ar)

[[1 7 2 3]
 [4 8 5 6]]


In [11]:
# append elements to the end of an array
array = np.array([1, 2, 3])
new_array = np.append(array, [4, 5])
print(new_array)

[1 2 3 4 5]


In [12]:
# concatenate two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concat_array = np.concatenate((array1, array2))
print(concat_array)

[1 2 3 4 5 6]


In [18]:
ar = np.array([10, 20, 30, 40, 50])

result = ar * 2  # Example of broadcasting
print(result)

ar1 = np.array([[1,2,3],[4,5,6]])
ar2 = np.array([10, 20, 30])
result_broadcast = ar1 + ar2  # Broadcasting addition
print(result_broadcast)

# for incompatible shapes, broadcasting will raise an error

ar3 = np.array([[1, 2, 3], [3, 4, 5]])
ar4 = np.array([10, 20])
# result_error = ar3 + ar4  # This will raise an error
temp = ar3.reshape(3,2)
result = temp + ar4  # Reshaping to make it compatible
print(result)


[ 20  40  60  80 100]
[[11 22 33]
 [14 25 36]]
[[11 22]
 [13 23]
 [14 25]]


In [ ]:
ar = np.array([10, 20, np.nan, 40, 50, np.nan])
# Check for NaN values
nan_mask = np.isnan(ar)
print("NaN values in array:", nan_mask)

# Count NaN values
nan_count = np.sum(nan_mask)
print("Number of NaN values:", nan_count)

# Replace NaN values with a specific value (e.g., 0)
ar_no_nan = np.nan_to_num(ar, nan=0)
print("Array with NaN replaced:", ar_no_nan)

# isinf checks for infinite values
ar_inf = np.array([1, 2, np.inf, 4, -np.inf])
inf_mask = np.isinf(ar_inf)
print("Infinite values in array:", inf_mask)

# Count infinite values
inf_count = np.sum(inf_mask)
print("Number of infinite values:", inf_count)

# Replace infinite values with a specific value (e.g., 100)
ar_inf_no_inf = np.where(np.isinf(ar_inf), 100, ar_inf)
print("Array with infinite values replaced:", ar_inf_no_inf)



NaN values in array: [False False  True False False  True]
Number of NaN values: 2
Array with NaN replaced: [10. 20.  0. 40. 50.  0.]
Infinite values in array: [False False  True False  True]
Number of infinite values: 2
Array with infinite values replaced: [  1.   2. 100.   4. 100.]
