Exercise 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

2.3.1


Exercise 2. How to create a 1D array?

In [8]:
ar1 = np.array([1, 2, 3, 4, 5]) # 1D array creation
print(ar1)

ar2 = np.arange(10) # 1D array creation
print(ar2)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


Exercise 3. How to create a boolean array?

In [11]:
# Question : Create a 3×3 numpy array of all True’s

# Solution
print(np.full((3,3), True, dtype=bool),"\n")

#or
print(np.full((9), True, dtype=bool).reshape(3,3),"\n")

#or
print(np.ones((3,3), dtype=bool),"\n")

#or
print(np.ones((9), dtype=bool).reshape(3,3))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Exercise 4. How to extract items that satisfy a given condition from 1D array?

In [12]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]


Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

In [13]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Exercise 6. How to replace items that satisfy a condition without affecting the original array?

In [14]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
out = arr.copy()
out [out % 2 == 1] = -1
print("out:", out)
print("arr:", arr)

out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
arr: [0 1 2 3 4 5 6 7 8 9]


Exercise 7. How to reshape an array?

In [ ]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])
arr = np.arange(10)
reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr, "\n")

#another way
reshaped_arr = arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1 2 3 4]
 [5 6 7 8 9]]


Exercise 8. How to stack two arrays vertically?

In [22]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print("a:\n", a)
print("b:\n", b)
vstacked = np.vstack((a, b))
print("\nAfter vertical stacking:\n", vstacked)

a:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

After vertical stacking:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Exercise 9. How to stack two arrays horizontally?

In [24]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print("a:\n", a)
print("b:\n", b)

hstacked = np.hstack((a, b))
print("\nAfter horizontal stacking:\n", hstacked)

a:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

After horizontal stacking:
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Exercise 10. How to generate custom sequences in numpy without hardcoding?

In [ ]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])
pattern1 = np.repeat(a, 3)  # Repeat each element of a 3 times
pattern2 = np.tile(a, 3)    # Repeat the entire array 3 times
# print("Pattern 1:\n", pattern1)
# print("Pattern 2:\n", pattern2)

final = np.hstack((pattern1, pattern2))
print("Final Pattern:\n", final)

Pattern 1:
 [1 1 1 2 2 2 3 3 3]
Pattern 2:
 [1 2 3 1 2 3 1 2 3]
Final Pattern:
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Exercise 11. How to get the common items between two python numpy arrays?

In [28]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a, b)
print("Common items:", common_items)

Common items: [2 4]


Exercise 12. How to remove from one array those items that exist in another?

In [29]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
ans = np.setdiff1d(a, b)
print("Items in a not in b:", ans)

Items in a not in b: [1 2 3 4]


Exercise 13. How to get the positions where elements of two arrays match?

In [32]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
matching_positions = np.where(a == b)
print("Matching positions:", matching_positions)
# Note: The output is a tuple containing the indices where the elements match.

#another way to find matching positions
matching_positions = np.where(np.isin(a, b))
print("Matching positions using np.isin:", matching_positions)

# output in list format
matching_positions_list = matching_positions[0].tolist()
print("Matching positions in list format:", matching_positions_list)

Matching positions: (array([1, 3, 5, 7]),)
Matching positions using np.isin: (array([1, 3, 5, 7]),)
Matching positions in list format: [1, 3, 5, 7]


Exercise 14. How to extract all numbers between a given range from a numpy array?

In [33]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)
a = np.array([2, 6, 1, 9, 10, 3, 27])
ans = a[(a >= 5) & (a <= 10)]
print("Items between 5 and 10:", ans)

Items between 5 and 10: [ 6  9 10]


Exercise 15. How to make a python function that handles scalars to work on numpy arrays?

In [38]:
# Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def pair_max(a, b):
    return np.maximum(a, b)


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
print("Pairwise maximum:", result)


""" Alternate solution:
def pair_max(a, b):
    maximum = [max(x, y) for x, y in zip(a, b)]
    return np.array(maximum) """


Pairwise maximum: [6 7 9 8 9 7 5]


' Alternate solution:\ndef pair_max(a, b):\n    maximum = [max(x, y) for x, y in zip(a, b)]\n    return np.array(maximum) '

Exercise 16. How to swap two columns in a 2d numpy array?

In [42]:
# Question: Swap columns 0 and 1 in the array arr.
ar = np.arange(9).reshape(3, 3)
print("Original array:\n", ar)
print("Swapping columns 0 and 1...")
print(ar[:, [1, 0, 2]])  # Swapping columns by indexing

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Swapping columns 0 and 1...
[[1 0 2]
 [4 3 5]
 [7 6 8]]


Exercise 17. How to swap two rows in a 2d numpy array?

In [43]:
# Question: Swap rows 0 and 1 in the array arr.
ar = np.arange(9).reshape(3, 3)
print("Original array:\n", ar)
print("Swapping rows 0 and 1...")
print(ar[[1,0,2], :])  # Swapping rows by indexing

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Swapping rows 0 and 1...
[[3 4 5]
 [0 1 2]
 [6 7 8]]


Exercise 18. How to reverse the rows of a 2D array?

In [ ]:
# Question: Reverse the rows of a 2D array arr. 
ar = np.arange(9).reshape(3, 3)
print("Original array:\n", ar)
print("Reversed rows:")
print(ar[::-1, :])  # Reversing rows using slicing

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed rows:
[[6 7 8]
 [3 4 5]
 [0 1 2]]


Exercise 19. How to reverse the columns of a 2D array?

In [47]:
# Question: Reverse the columns of a 2D array arr.
ar = np.arange(9).reshape(3, 3)
print("Original array:\n", ar)
print("Reversed columns:")
print(ar[:, ::-1])  # Reversing columns using slicing

Original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed columns:
[[2 1 0]
 [5 4 3]
 [8 7 6]]


Exercise 20. How to create a 2D array containing random floats between 5 and 10?

In [48]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
randon_arr = np.random.uniform(5,10,size=(5,5))
print("Random array with shape 5x5 containing numbers between 5 and 10:\n", randon_arr)

Random array with shape 5x5 containing numbers between 5 and 10:
 [[7.92048779 9.12359653 5.66265171 6.15747686 9.22417453]
 [6.41397854 6.70507678 7.08234223 9.0228348  8.1356985 ]
 [8.50187917 8.35240258 8.71830996 5.02595437 7.36010139]
 [5.93475378 6.35402692 6.27359082 5.41031351 9.49418158]
 [6.86104381 6.97253543 7.96392662 6.43769928 6.40831769]]


Extra: ravel, flatten

In [ ]:
"""
ravel --> create a view of the array in 1D that reflects changes in the original array
flatten --> create a copy of the array in 1D that does not reflect changes in the original array
"""

import numpy as np
ar = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", ar)
print("Ravelled array (view):", ar.ravel()) 
print("Flattened array (copy):", ar.flatten())


# Fancy Indexing(Select multiple values at a time)
ar = np.array([10,20,30,40,50,60])
print(ar[[1, 3, 4]])  # Accessing elements at indices 1, 3, and 4: [20, 40, 50]

Original array:
 [[1 2 3]
 [4 5 6]]
Ravelled array (view): [1 2 3 4 5 6]
Flattened array (copy): [1 2 3 4 5 6]
[20 40 50]
