✅ 1D NumPy Array Slicing : array[start:stop:step]

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

In [3]:
print(arr[1:4])      # [20, 30, 40]
print(arr[:3])       # [10, 20, 30]
print(arr[3:])       # [40, 50, 60]
print(arr[:])        # [10, 20, 30, 40, 50, 60]

[20 30 40]
[10 20 30]
[40 50 60]
[10 20 30 40 50 60]


In [4]:
print(arr[::1])      # [10, 20, 30, 40, 50, 60]
print(arr[::2])      # [10, 30, 50]
print(arr[1:5:2])    # [20, 40]

[10 20 30 40 50 60]
[10 30 50]
[20 40]


In [5]:
#Negative slicing
print(arr[-3:])      # [40, 50, 60]
print(arr[:-2])      # [10, 20, 30, 40]

[40 50 60]
[10 20 30 40]


In [6]:
#reverse slicing
print(arr[::-1])     # [60, 50, 40, 30, 20, 10]
print(arr[-1])       # 60
print(arr[-2:])      # [50, 60]
print(arr[-3:-1])    # [40, 50]

[60 50 40 30 20 10]
60
[50 60]
[40 50]


✅ 2D NumPy Array Slicing: array[row_start:row_stop, col_start:col_stop]

In [7]:
arr2d = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])
print(arr2d)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [10]:
print(arr2d[0])       # First row: [11, 12, 13, 14]
print(arr2d[1:3])     # Rows 1 and 2

[11 12 13 14]
[[21 22 23 24]
 [31 32 33 34]]


In [12]:
print(arr2d[:, 0])    # First column: [11, 21, 31, 41]
print(arr2d[:, 2:4])  # Columns 2 and 3

[11 21 31 41]
[[13 14]
 [23 24]
 [33 34]
 [43 44]]


In [13]:
print(arr2d[0, 1:3])  # First row, columns 1 and 2: [12, 13]
print(arr2d[1:3, 1])  # Rows 1 and 2, column 1: [22, 32]
print(arr2d[1:3, 1:3])  # [[22, 23], [32, 33]]

[12 13]
[22 32]
[[22 23]
 [32 33]]


In [14]:
print(arr2d[::2, ::2])  # [[11, 13], [31, 33]]


[[11 13]
 [31 33]]


In [ ]:
print(arr2d[::-1, :])   # Reverse rows
print('-' * 20)  

print(arr2d[:, ::-1])   # Reverse columns
print('-' * 20)   

print(arr2d[::-1, ::-1])  # Reverse entire matrix


[[41 42 43 44]
 [31 32 33 34]
 [21 22 23 24]
 [11 12 13 14]]
--------------------
[[14 13 12 11]
 [24 23 22 21]
 [34 33 32 31]
 [44 43 42 41]]
--------------------
[[44 43 42 41]
 [34 33 32 31]
 [24 23 22 21]
 [14 13 12 11]]
